// =============================================================================
// THE FOUR EXHIBITIONS — this is the file to edit for wording, dates and names.
// =============================================================================
//
// /Events is one long scroll with four parts, in this order:
//
//   1. Fractal          Taipei        November 2022
//   2. Honk, Please!    Hyderabad     April 2023
//   3. Borde_           Buenos Aires  December 2023
//   4. Chimera          Berlin        January 2025
//
// Every word on that page comes from this file. The page reads this and nothing
// else, so there is no second copy of any of it to keep in sync.
//
// -----------------------------------------------------------------------------
// EDITING TEXT
// -----------------------------------------------------------------------------
// Change what is inside the quote marks. Keep the quote marks, the commas and
// the square brackets exactly where they are.
//
// Where you see a list of paragraphs like this:
//
//   body: ["First paragraph.", "Second paragraph."],
//
// each item is one paragraph, with a blank line between them on the page. Add
// one by copying an item; remove one by deleting it (and its comma).
//
// -----------------------------------------------------------------------------
// PICTURES
// -----------------------------------------------------------------------------
// Pictures are referred to by a short name, like "honk/img-4819". Those names
// come from src/components/events/event-images.ts, which is generated by
// scripts/fetch-event-assets.mjs and should not be edited by hand. If you type
// a name that does not exist, the site refuses to build rather than showing a
// broken picture, so a typo can never reach the live page.
//
// `alt` is the description read aloud to somebody who cannot see the picture.
// Say what is in it, plainly, in a sentence. These were written from each
// zone's own description rather than by studying every photograph, so improve
// any that read as vague — that is a real improvement, not a nitpick.
//
// -----------------------------------------------------------------------------
// WORDING CHANGED FROM THE OLD CARGO SITE
// -----------------------------------------------------------------------------
// Four clear slips were corrected while moving this across. Nothing else was
// touched — every other sentence is word for word as it was.
//
//   Zone 3    "...hang their creations oncelets, to simulate the auto
//             experience." A fragment of zone 1 & 2's text had been pasted onto
//             the end of this sentence. Now ends "...hang their creations on."
//   Zone 4&5  "collected in thr city"        -> "collected in the city"
//   Zone 7a   "art supplie, box"             -> "art supplies, box"
//   Zone 7a   an opening bracket was never closed; the list now closes it.
//
// The Borde_ date is another such decision, and a deliberate one. The old
// Events index said November 2023 while the Borde_ page itself said
// December 02, 2023. The exhibition page is the more specific of the two and
// was written by the people who ran it, so December is what is used here and
// on the navigation rail. If November is right, change it in this file and it
// changes everywhere.
//
// =============================================================================

import type { EventImageKey } from "./event-images";

export type ActId = "fractal" | "honk" | "borde" | "chimera";

/** A picture, wherever one appears in the four exhibitions. */
export type Picture = {
  image: EventImageKey;
  alt: string;
};

/** The rail down the side of the page, and the order the parts scroll past in.
 *  `id` is also the address of that part: /Events#fractal, /Events#honk, and
 *  so on. Changing an id changes those links, so leave them alone unless you
 *  mean to. */
export const ACTS: { id: ActId; label: string; place: string; date: string }[] = [
  { id: "fractal", label: "Fractal", place: "Taipei, Taiwan", date: "November 2022" },
  { id: "honk", label: "Honk, Please!", place: "Hyderabad, India", date: "April 2023" },
  { id: "borde", label: "Borde_", place: "Buenos Aires, Argentina", date: "December 2023" },
  { id: "chimera", label: "Chimera", place: "Berlin, Germany", date: "January 2025" },
];

// -----------------------------------------------------------------------------
// 1. FRACTAL
// -----------------------------------------------------------------------------

export const FRACTAL = {
  eyebrow: "Interactive Exhibition",
  title: "Fractal",
  place: "Taipei, Taiwan",
  date: "November 2022",
  lede: "Welcome to Fractal, Napkins’ inaugural interactive exhibition.",
  intro: [
    "Fractal is an infinitely repeating pattern.",
    "We see fractals in our surroundings. Waves. Snowflakes. Tree branches.",
    "Zoom in or zoom out, the patterns repeat themselves.",
    "",
    "Fractal is the line between order and chaos.",
    "In this interactive exhibition, we prioritize the unleashing of chaos within the participants’ minds",
    "and the materialization of the chaos onto napkins.",
  ],
  video: {
    file: "fractal/lungs-video" as const,
    caption: "A projection of the bronchial fractal shown in the Lungs room.",
  },
  spacesHeading: "Explore Spaces",
};

// -----------------------------------------------------------------------------
// 2. HONK, PLEASE!
// -----------------------------------------------------------------------------

export type Zone = {
  /** the number as it was painted on the floor plan — "0", "1 & 2", "7a" */
  number: string;
  name: string;
  body: string[];
  design?: string[];
  materials?: string;
  designer: string;
  pictures: Picture[];
  /** true where the original centred the pictures in their column */
  centred?: boolean;
};

export const HONK = {
  eyebrow: "Interactive Art Exhibition",
  title: "Honk, Please!",
  place: "Lamakaan, Hyderabad, India",
  date: "April 02, 2023",
  lede: "Welcome to Honk, Please!",
  intro: [
    "The first time we rode an auto, we gripped the handle. We held on to our friends. The thrill of the drives mixed with the fear for our lives. But the fear soon turned as visceral as a passing breeze. Distances in the city narrowed on the map with a moving green and yellow square. Distances between us closed with a ride. We move in the city. We move with autos.",
    "Honk, Please! Remind me of how I first felt. How I still feel.",
  ],
  /** the original puts a horizontal rule between the two halves of the intro */
  introAfterRule: [
    "Honk, Please! is Napkins’ second interactive art exhibition where visitors are still the creators and curators. Napkins is an art and literary organization at Minerva University—a traveling university. Artists, writers, poets, students, working adults, retirees—whether making something creative is a first or part of your everyday routine—come together in this space. At Honk, Please!, visitors will experience different creative spaces centered around the theme of autorickshaws. All spaces involve participants creating something, anything—with words or pictures, verbal or non-verbal. Every creation will be curated into final installations whose forms will only be determined as the creation occurs.",
  ],
  floorPlan: {
    heading: "Floor Plan",
    image: "honk/screenshot-2025-01-27-at-23-17-37" as EventImageKey,
    alt: "Two hand-drawn plans of the Lamakaan courtyard side by side. The left is a line drawing with the zones numbered 1 to 7b in red; the right repeats it with each zone washed in a different colour. A key at the foot reads “= trees”.",
  },
  zones: [
    {
      number: "0",
      name: "Starting: Intro",
      body: [],
      design: ["A long piece of drawing/artwork drawn on the stairs leading down to the exhibition space."],
      materials: "Chalks; colorful ones.",
      designer: "Dariia Panasenko",
      pictures: [
        {
          image: "honk/screenshot-2025-01-27-at-23-19-53",
          alt: "A sketch of the staircase down into the exhibition, its steps loosely coloured in.",
        },
      ],
    },
    {
      number: "1 & 2",
      name: "At Home with Friendship Bracelet",
      body: [
        "This place focuses on elements of “home” & idleness as one waits for the ride. Participants make friendship bracelets while waiting to get into the auto. They need to have 4 numbers on the friendship bracelets, to resemble an Uber/Ola pin. Before they enter the auto, they will show the “driver” (aka someone that checks the PIN) their friendship bracelets, to simulate the auto experience.",
      ],
      design: [
        "- Cafe/Bar-like area (e.g., Terrasen + At Home Serviced Apartment + Shilparamam)",
        "- Tapestry on low tables that serve as seating areas.",
      ],
      materials: "Tapestries, color beads, string, scissors",
      designer: "Zhi Zhi Chia, Htet Yuya, Jan Johannsmann",
      pictures: [
        {
          image: "honk/img-4819",
          alt: "Visitors sitting close together at low tables in the courtyard, threading coloured beads onto string, with an auto-rickshaw parked behind them.",
        },
        {
          image: "honk/img-4797",
          alt: "A low table covered with a patterned tapestry, scattered with beads, scissors and half-finished friendship bracelets.",
        },
      ],
    },
    {
      number: "3",
      name: "Auto Rides",
      body: [
        "Participants enter the auto and put on earphones (like what auto drivers do!). They will listen to a random clip of messages. All these clips add up to a coherent story (narrated by Yuya), but they are not played in a linear order. After participants listen to one clip, they will write/draw/create their interpretation and attach them to the wire surrounding the autos. The final product will show how different interpretations can form a grander image.",
        "The wire structure surrounding the auto is to form an enclosure that signals the visitors getting into a different world. It’s also a structure for the visitors to hang their creations on.",
      ],
      design: ["Auto with metal wire hung on the tree trunks next to the auto."],
      materials: "Auto, iPads, earphones, audio clips, string, clips",
      designer: "Htet Yuya, Cassandra Marguerit Cruz, Zhi Zhi Chia",
      centred: true,
      pictures: [
        {
          image: "honk/img-4875",
          alt: "A visitor lying back across the seat of a green and yellow auto-rickshaw, laughing, with earphones in.",
        },
        {
          image: "honk/img-4986",
          alt: "Written and drawn responses pegged to a wire strung between tree trunks around the parked auto.",
        },
      ],
    },
    {
      number: "4 & 5",
      name: "Zoned Out Ride",
      body: [
        "Auto rides can be very sensorily overwhelming and one can space out. This featured printed posters from different rotation cities for Minerva, but in MSCHF blur style. Having blurred posters from different cities also point to the idea that the roads in India aren’t that different from our homes. When the visitors stepped out of the auto, they will immediately be met with the panels and posters. On the floor, we will have different trinkets and ornaments collected in the city.",
      ],
      design: [
        "Blurred posters of landmarks from the 7 rotation cities for Minerva University, arranged arbitrarily in the empty space, almost maze-like.",
      ],
      materials: "Posters, pots, sticks, ornament, small statues, chalks.",
      designer: "Dariia Panasenko, Zhi Zhi Chia, Sun Kim",
      centred: true,
      pictures: [
        {
          image: "honk/img-4949",
          alt: "Blurred posters of city landmarks hung at angles across a white wall, with small clay pots and trinkets set out on the floor beneath them.",
        },
        {
          image: "honk/img-4775",
          alt: "A visitor walking between the hanging poster panels, seen from behind.",
        },
      ],
    },
    {
      number: "7a",
      name: "Destination: Origami Letters",
      body: [
        "This area is meant to be low energy and reflective. Situated at an elevated area with an overall view of the exhibition, visitors had access to letters, crayons, pens, and color pencils to write letters, either to no one or to someone who the Exhibition Team would deliver to post-exhibition.",
      ],
      design: ["Tables with chairs."],
      materials:
        "Papers (colors, white, napkins/recycled materials), scissors, marker, pen, color pencils, art supplies, box (to collect letters)",
      designer: "The whole team",
      pictures: [
        {
          image: "honk/img-4936",
          alt: "Visitors writing letters at a table on the raised terrace, looking down over the rest of the exhibition.",
        },
      ],
    },
    {
      number: "7b",
      name: "Destination: General writing/drawing/creating area",
      body: [
        "This area is meant to be low energy and reflective. Visitors can sit here and create whatever they want, inspired by everything they observe. From this area, they get a top-down view of the whole exhibition, which is the perfect place to consolidate their thoughts.",
      ],
      design: ["Tables with chairs."],
      materials: "Napkins, markers, pen, color pencil, art supplies",
      designer: "The whole team",
      pictures: [
        {
          image: "honk/img-4912",
          alt: "Napkins and drawings spread across a table, with visitors working on them and the courtyard visible below.",
        },
      ],
    },
  ] satisfies Zone[],
  photosLink: "More Photos",
};

/** The "More Photos" page, at /Events/honk-please/photos.
 *
 *  Cargo laid these out with its "Freeform" gallery, which here meant a strict
 *  alternation: every other photograph is two thirds of the width and the ones
 *  between are one third, so they pair up across the page. That alternation is
 *  computed from the position in this list rather than written out, so adding
 *  or removing a photograph re-pairs the rest on its own.
 *
 *  This page is the one part of the section set on black rather than white —
 *  that is how the original was, and it suits a room of photographs. */
export const HONK_PHOTOS = {
  eyebrow: "Honk, Please!",
  title: "Photographs",
  credit: "Photographs by Mona Westphal",
  photos: [
    { image: "honk-photos/img-4919-01", alt: "A visitor pegging a green note to a line strung under a tree, a “NO SMOKING” sign on the wall behind them." },
    { image: "honk-photos/img-4754-02", alt: "A visitor crouching on stone steps that are covered end to end in chalk drawing, adding to it." },
    { image: "honk-photos/img-4986", alt: "A visitor sitting inside the auto-rickshaw writing on a slip of paper, pink notes pegged to a wire overhead." },
    { image: "honk-photos/img-4968", alt: "Two visitors crouched on the ground by a red wall, blank sheets pinned above them and small clay pots at their feet." },
    { image: "honk-photos/img-4960", alt: "The green and yellow auto parked under trees, visitors sitting on chairs beside it, coloured notes strung between the branches." },
    { image: "honk-photos/img-4949", alt: "Blurred posters of city landmarks taped across a white wall, with terracotta pots scattered on the ground in front." },
    { image: "honk-photos/img-4936", alt: "Visitors sitting on and around a large boulder in the leafy courtyard, materials spread on chairs nearby." },
    { image: "honk-photos/img-4912", alt: "Two visitors standing close together, heads bent over something small held between them." },
    { image: "honk-photos/img-4908", alt: "A visitor resting their head on the table as they write, a tray of coloured markers beside their hand." },
    { image: "honk-photos/img-4899", alt: "People gathered at a table covered in coloured paper, one of them folding a sheet." },
    { image: "honk-photos/img-4892", alt: "A visitor in headphones sitting in the auto's driver seat, a tablet propped in front of them and notes stuck to the frame." },
    { image: "honk-photos/img-4890", alt: "A group around a low table making friendship bracelets, plates of beads set out between them." },
    { image: "honk-photos/img-4875", alt: "A visitor laughing, sitting sideways across the auto's passenger seat." },
    { image: "honk-photos/img-4855", alt: "A hand reaching up to peg pink and yellow notes onto a line strung across the courtyard." },
    { image: "honk-photos/img-4853", alt: "A close view of handwritten notes pegged to a line, one filled edge to edge with writing." },
    { image: "honk-photos/img-4836", alt: "A visitor in a patterned bandana standing beside the auto with string in her hands." },
    { image: "honk-photos/img-4819", alt: "A crowd seated along low tables working on bracelets, with the autos and hanging posters behind them." },
    { image: "honk-photos/img-4808", alt: "A close view of a visitor knotting a bracelet thread." },
    { image: "honk-photos/img-4797", alt: "A group leaning in over a table, making bracelets together." },
    { image: "honk-photos/img-4787", alt: "Visitors at a table threading beads onto lengths of string." },
    { image: "honk-photos/img-4784", alt: "Two visitors side by side, one laughing while the other concentrates on knotting a bracelet." },
    { image: "honk-photos/img-4776", alt: "A chalk drawing of an auto-rickshaw on dark stone, with “HONK” written beneath it." },
    { image: "honk-photos/img-4775", alt: "Terracotta pots tipped over on the ground, spilling earth across chalk lines." },
    { image: "honk-photos/img-4774", alt: "A visitor crouching to right a tipped clay pot, chalk marks drawn around it on the floor." },
    { image: "honk-photos/img-4770", alt: "The auto's windscreen seen from inside, a yellow “Hello!” note and pink slips stuck to the glass, headphones resting on the dash." },
  ] satisfies Picture[],
};

// -----------------------------------------------------------------------------
// 3. BORDE_
// -----------------------------------------------------------------------------

export const BORDE = {
  eyebrow: "Interactive Exhibition & Workshops",
  title: "Borde_",
  place: "Museo de Arte Contemporáneo de Buenos Aires (MACBA), Argentina",
  date: "December 02, 2023",
  lede: "Welcome to Borde_",
  intro: [
    "Borde_ is Napkins’ third interactive arts exhibition. *Borde* in Spanish means “edge.” It is lines that decide an in and an out. Lines that determine where your comfort ends and begins. *Borde* is also a feeling. Feeling on “edge”. How do you define your *borde*? What are your boundaries? What puts you on edge? Borde__ is a deconstruction of the boundaries in our lives, from labels to personal space. What separates and connects us?",
  ],
  walkthrough: {
    heading: "Walk through the Exhibition",
    // The original embeds this straight from YouTube. It is loaded only after
    // the visitor asks for it — see the note in EventVideo.
    youtubeId: "nRviXTonIzk",
    title: "Walk through the Borde_ exhibition at MACBA, Buenos Aires",
  },
  creditsHeading: "Credits",
  credits: [
    { role: "Director", names: "Dasha Panasenko" },
    { role: "Creative Director", names: "Zhi Zhi Chia" },
    { role: "Even Curators", names: "Shawn Lee, Evan Wolfe, Polina Zen" },
    { role: "Finance Administrator", names: "Jan Johannsmann" },
    { role: "Translators", names: "Marta Borrell Fijo, Alan Mariño" },
    { role: "Photographer", names: "Htet Yuya" },
    { role: "Videographer", names: "Paulina Lee" },
    { role: "Cocktail Bar Master", names: "Lucille Glassman" },
  ],
  thanksHeading: "Special thanks to",
  thanks: ["MACBA", "Fátima Rubino", "Sun Kim", "Ignatio de Witte", "Jan de Witte", "Tergel Sukhbaatar"],
};

// -----------------------------------------------------------------------------
// 4. CHIMERA
// -----------------------------------------------------------------------------

export const CHIMERA = {
  eyebrow: "Interactive Exhibition & Workshops",
  title: "Chimera: What Stories Does Your Body Tell?",
  place: "Migrant Bird Space, Berlin",
  date: "January 16 - 18, 2025",
  lockup: {
    image: "chimera/x-2" as EventImageKey,
    alt: "The Napkins logo beside the Migrant Bird Space logo, joined by a multiplication sign.",
  },
  lede: "Welcome to Chimera",
  intro: [
    "In Greek mythology, the Chimera is a fire-breathing creature that is composed of different beings. Its hybrid form symbolizes the blending of disparate elements, evoking the complexity of postcolonial identities. Postcolonial theorist Homi K. Bhabha argues that identity formation occurs not through simple binaries—colonizer/colonized, East/West—but within a dynamic “third space.” This space of in-betweenness is where cultures intersect, negotiate, and create new meanings. The process of negotiation is full of contradictions many of us experience phenomenologically, from the perspective of our bodies and lived experiences.",
    "Identity is not just an intellectual construct; it is embodied and lived. It manifests in moments of connection, like finding belonging in shared cultural practices, and moments of dissonance, such as confronting language, behaviors, or perceptions that challenge our sense of self. These feelings, whether joy, discomfort, pride, or alienation, remind us that identity is fluid, shaped by memory, history, and our present realities. It reveals itself in the spaces we inhabit and the ways we navigate an ever-shifting world.",
    "In Berlin, many of us embody the Chimera. We carry elements that affirm our identity while grappling with others that disrupt it. Yet, these tensions do not fracture us. Instead, they coexist, creating a multifaceted wholeness. Our contradictions are not irreconcilable—they are the essence of our identity.",
    "Chimera invites you to explore your own hybrid identity and consider how you contribute to Berlin’s ever-shifting mosaic. Through interactive art and reflection, discover how we, as individuals and a city, are transformed by our contradictions and connections. Welcome to Chimera—a space to embrace the beauty and questions of being in-between.",
  ],
  diaspora: {
    heading: "In conversation with DIASPORA BIRDS",
    body: "DIASPORA BIRDS is a photography series by renowned Chinese photographer Luo Yang. Currently exhibiting at Migrant Bird Space, DIASPORA BIRDS explores the Asian diaspora experience in Europe. Featuring individuals from China, Vietnam, Indonesia, the Philippines, Cambodia, and other nations, the series includes first and second-generation immigrants, LGBT individuals, orphans adopted into Europe, political refugees, and recent students who have chosen to stay. Luo Yang’s work not only documents the external lives of these individuals, but also delves into their internal spiritual journey. Through her lens, Luo Yang aims to capture the emotional complexities and resilient spirits of those navigating life in a foreign land, inviting viewers to connect with their unique experiences at the intersection of cultures.",
    byline: "written by Zhi Zhi Chia",
  },
  audioGuide: {
    heading: "Audio Guide",
    body: "Who is Chimera? Why are we here? Listen to the audio guide.",
  },
  teamHeading: "Meet the Team",
  teamIntro: [
    "We are a group of friends from Malaysia, Ukraine, Germany, and Korea, who first met as students traveling and learning together across seven cities worldwide. Our shared experiences of navigating unfamiliar places, cultures, and ideas sparked conversations about identity, belonging, and transformation—questions that continue to inspire us today.",
    "Though our paths began in different parts of the world, we quickly found common ground in our curiosity for exploring the in-between spaces of life: where cultures meet, where identities shift, and where contradictions create something new. In Berlin, a city that thrives on its multiplicity, we find a space that mirrors our collective ethos.",
    "Through Chimera, we invite you into our shared exploration of what it means to belong, to challenge dissonance, and to embrace contradiction.",
  ],
  // This team block belongs to Chimera only — it is not the Napkins roster on
  // /About-Us, which lives in src/components/about/team-data.ts.
  team: [
    {
      name: "Zhi Zhi",
      flag: "🇲🇾",
      pronouns: "she/her",
      roles: ["Curator", "Exhibition Manager"],
      email: "zhizhi@uni.minerva.edu",
      image: "chimera/continuum-square" as EventImageKey,
    },
    {
      name: "Shawn",
      flag: "🇰🇷",
      pronouns: "she/her",
      roles: ["Curator", "Brand Manager"],
      email: "shawnlee@uni.minerva.edu",
      image: "chimera/screenshot-2024-06-16-at-16-30-28" as EventImageKey,
    },
    {
      name: "Polina",
      flag: "🇺🇦",
      pronouns: "they/them",
      roles: ["Curator", "Artistic Director"],
      email: "zen@uni.minerva.edu",
      image: "chimera/polina" as EventImageKey,
    },
    {
      name: "Dasha",
      flag: "🇺🇦",
      pronouns: "she/her",
      roles: ["Curator", "Visual & Experiential Designer"],
      email: "dariia@uni.minerva.edu",
      image: "chimera/dasha-square" as EventImageKey,
    },
    {
      name: "Jan",
      flag: "🇩🇪",
      pronouns: "he/him",
      roles: ["Curator", "Finance Administrator"],
      email: "johannsmann@uni.minerva.edu",
      image: "chimera/jan" as EventImageKey,
    },
  ],
  thanksHeading: "Special thanks to",
  thanks: [
    { name: "Htet Yuya", for: "for voicing Chimera." },
    { name: "Mika-Erik Möser", for: "for transcribing the audio clips." },
    { name: "Pelle van Dam", for: "for helping with Box Box Box." },
    { name: "Stephanie Froebel", for: "for helping with exhibition setup." },
    { name: "Prof. Jon Wilkins", for: "for suggesting the name Chimera." },
  ],
  partner: {
    heading: "Migrant Bird Space",
    href: "https://www.migrantbirdspace.com/",
    body: [
      "Migrant Bird Space is a Berlin- & Beijing-based art foundation and gallery, providing a showcase for artists as well as art-agency services in China and Europe. Working out of the gallery space at Koppenplatz in the heart of Berlin, the foundation offers a professional platform for cross-cultural communication between China and Europe with a focus on contemporary Chinese art.",
      "Promoting both established and emerging artists, Migrant Birds provides gallery spaces for exhibitions in Berlin, Beijing, and Shanghai, an artist-in-residence program, regular talks and lectures, as well as support in liaising with museums, universities, private institutions and more.",
    ],
  },
  contact: {
    heading: "Contact Us",
    instagram: "napkinseverywhere",
    email: "napkinseverywhere@gmail.com",
  },
  colophon: ["Illustration by Dariia Panasenko", "Web Design & Curation by Zhi Zhi Chia"],
};
